name: ppp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - notebook
  - mkl
  - graphviz
  - seaborn
  - pydot
  - matplotlib
  - arviz
  - theano-pymc 
  - pymc3
  - scipy
  - pandas
  - numpy
  - mkl-service
  - watermark
  - jupyter
